project:
  type: website

website:
  title: "Yijia Zhao"
  navbar: 
    left:
      - href: posts.qmd
        text: Posts
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    theme-toggle:
      location: navbar
      default-appearance: auto
    css: styles.css
    code-copy: true
    toc: true
    toc-location: right
    mathjax: true
