project:
  type: website

website:
  title: "Yijia Zhao"
  navbar: 
    left:
      - href: posts.qmd
        text: Posts
format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
    mathjax: true