project:
  type: website
  resources: 
    - assets/

website:
  title: "Yijia Zhao"
  navbar: 
    left:
      - icon: file-post
        href: posts.qmd
        text: Posts
      - icon: info-circle
        href: credits.qmd
        aria-label: "Credits"
  search:
    location: navbar
    type: overlay
    copy-button: true
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    theme-toggle:
      location: navbar
      default-appearance: auto
    css: styles.css
    code-copy: true
    toc: true
    toc-location: right
    mathjax: true
